export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_RESOLVED = "FETCH_USER_RESOLVED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";
export const ADD_USER = "ADD_USER";
