export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const FETCH_TODO_RESOLVED = "FETCH_TODO_RESOLVED";
export const FETCH_TODO_REJECTED = "FETCH_TODO_REJECTED";
export const ADD_TODO = "ADD_TODO";
